site_name: Trustfall
site_description: "The documentation for Trustfall, a query engine for any combination of data sources."
repo_url: "https://github.com/obi1kenobi/trustfall"
repo_name: "obi1kenobi/trustfall"
site_url: https://trustfall.dev/
edit_uri: "edit/main/docs/"
plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": "overview/index.md"
theme:
  name: material
  # logo: TODO
  # favicon: TODO
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - "Welcome":
    - "overview/index.md"
  - "Getting Started": "getting_started/index.md"
  - "Language Reference":
    - "language_reference/index.md"
    - "Glossary": "language_reference/glossary.md"
    - "Schema":
      - "language_reference/schema/index.md"
    - "Querying":
      - "language_reference/querying/index.md"
      - "Examples": "language_reference/querying/examples.md"
      - "Directives":
        - "@output": "language_reference/querying/output.md"
        - "@filter": "language_reference/querying/filter.md"
        - "@tag": "language_reference/querying/tag.md"
        - "@optional": "language_reference/querying/optional.md"
        - "@recurse": "language_reference/querying/recurse.md"
        - "@fold": "language_reference/querying/fold.md"
        - "@transform": "language_reference/querying/transform.md"
      - "Type Coercions": "language_reference/querying/type_coercion.md"
      - "Edge Parameters": "language_reference/querying/edge_parameters.md"
